require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/posts" do
  describe "GET /index" do
    it "renders a successful response" do
      Post.create
      http_client = HTTPClient.new
      http_client.base_url = 'http://localhost:5000'
      response = http_client.get '/posts', header: {'Accept' => 'application/json'}
      expect(JSON.parse(response.body).size).to eq(1)
    end
  end
end
